export const GA_TRACKING_ID = 'UA-204337324-1'

export const PAGE_TAGS = {
  BLOGS: 'BLOGS'
}

export const CLICK_EVENT_TAG_NAMES = {
  MENU: 'MENU_CLICK',
  E_LINK: 'EXTERNAL_LINK',
  TOC_LINK: 'EXTERNAL_LINK',
}